name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: build on macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-macos
          path: binaries/*/*.exe

  build-linux:
    name: build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Install gcc-multilib
        run: sudo apt install gcc-multilib g++-multilib

      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-linux
          path: binaries/*/*.exe

  build-windows:
    name: build on Windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-windows
          path: binaries/*/*.exe
