name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: build on macOS
    runs-on: macos-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-macos
          path: binaries/*/*

  build-ios:
    name: build for ios
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Select Xcode
#        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Show SDK path
        run: xcrun --sdk iphoneos --show-sdk-path

      - name: Build
        run: ./build_ios

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-ios
          path: binaries/*/*

  build-linux:
    name: build on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - name: Install gcc-multilib
        run: sudo apt install gcc-multilib g++-multilib

      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-linux
          path: binaries/*/*

  build-windows:
    name: build on Windows
    runs-on: windows-2019

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries-windows
          path: binaries/*/*.exe
