name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: build on macOS
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries.zip
          path: binaries.zip