name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    name: build on macOS
    runs-on: macos-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v4

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries-macos
          path: binaries/*/*

  build-ios:
    name: build for ios
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

#      - name: Show SDK path
#        run: xcrun --sdk iphoneos --show-sdk-path
#
#      - name: ls
#        run: ls /Applications

      - name: Build
        run: ./build_ios

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries-ios
          path: binaries/*/*

  build-android:
    name: build for android
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./build_android

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries-android
          path: binaries/*/*

  build-linux:
    name: build on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: ilammy/setup-nasm@v1
      - name: Install gcc-multilib
        run: sudo apt install gcc-multilib g++-multilib

      - uses: actions/checkout@v4

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries-linux
          path: binaries/*/*

  build-windows:
    name: build on Windows
    runs-on: windows-2019

    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v4

      - name: Build
        run: python3 build.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows
          path: |
            binaries/*/*.exe
            binaries/*/*.dll
